--replace-in-metadata "title,playlist,playlist_title" "&" "and"
--replace-in-metadata "title,playlist,playlist_title" "\!" ""
--replace-in-metadata "title,playlist,playlist_title" ":" " -"
--replace-in-metadata "title,playlist,playlist_title" "\|" "-"
--replace-in-metadata "title,playlist,playlist_title" "\'" ""
